### ISSUE TITLE
Feature: anchor links

### ISSUE THREAD

**Issue by ryantm** [ryantm/mmdoc#17]
Add links to the page so people can link to anchors on sub-headings.

**Comment by samueldr** [comment]
The automatic ID generation should be compatible with GitHub's

Arbitrary title:

 - https://github.com/ryantm/mmdoc/blob/main/doc/usage.md#extensions-beyond-commonmark

Not sure I have any profound reason to think so.

**Comment by ryantm** [comment]
I think I'm currently opposed to automatic ID generation.

**Comment by samueldr** [comment]
The main argument *for* automatic ID generation is to lessen the burden of the documentation author. Right now to allow anyone to link to any sub-heading, the author would need to add an ID to all sub-heading.

But I do see why it sucks badly: changing the title changes the ID! So links become stale! But in reality I don't think this is much of an issue since if I rename a section, as an author, I will be tempted to also rename the ID to match!

Am I missing something?

**Comment by jtojnar** [comment]
Well, having the ID explicit would hopefully make the person editing think about whether to change the anchor, rather than changing it by accident unknowingly.

Another issue is that automatic IDs could create conflicts if we were to use them for linking across the book (we have already seen that several times during the Nixpkgs manual Markdown conversion). The alternative would be using full `file#anchor` links but that would couple the links to the structure even further.

**Comment by ryantm** [comment]
For now, I've added explicit anchor links.

**Comment by ryantm** [comment]
Reopening this because right now it only works properly for the top-level page.

**Comment by ryantm** [comment]
Okay that's fixed now.
